fixing annoying quirk with bash where functions aren't exported by default.
The fix means that this app will only really work with bash. To work around this we should probably stop using bash functions as part of the workflow going forward and just move toward executables

diff --git a/home/run b/home/run
--- a/home/run
+++ b/home/run
@@ -4,6 +4,11 @@ function dkr-rn {
 	set -m
 	"${DKR_DOCKER_COMMAND}" run "$@" &
 	2>/dev/null 1>/dev/null dkr-portmap
+
+	if [ "$?" != "0" ]; then
+		err "Could not map ports\!"
+	fi
+
 	2>/dev/null 1>/dev/null fg
 }
 
@@ -16,3 +21,7 @@ function dkr-rn-help_ {
 	echo ""
 	dkr-rn-summary_
 }
+
+export -f dkr-rn
+export -f dkr-rn-summary_
+export -f dkr-rn-help_
